### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by drtiwarir** [phpbg/watchtv#4]
Can you please explain how it works and what I need to set up .
I live in Australia, I want to watch streams from India, I have Linux servers from Digital Ocean & AWS in India. Do I need any hardware ?
I am having Digital TV subscription in India (have user ID & Password)
You help is appreciated
Thanks

**Comment by phpbg** [comment]
Hi,

this software allows you to receive digital tv with a hardware receiver (and of course an antenna).

Please see [documentation](https://github.com/phpbg/watchtv#server).

Is this what you're really loonking for?
